Newbranch
PGDimitrov/PetarDimitrov pull request #2
Opened 2022-05-28 16:33 UTC by PGDimitrov

Fix for negative values for exercise PrintTheBiggestArrayElement

2022-05-28 20:06 UTC, valyo-nikolov requested changes

2022-05-28 20:06 UTC, valyo-nikolov commented on src/homework_Lesson_5/ProgramValidatesPalindrome.java
> +        if (word.charAt(i) != word.charAt(word.length()-i-1)) {
ок пробвай с този текст: 'rapecar'
това не е палиндром, но ще изпише че е

2022-05-29 07:41 UTC, PGDimitrov commented on src/homework_Lesson_5/ProgramValidatesPalindrome.java
> +        if (word.charAt(i) != word.charAt(word.length()-i-1)) {
@valyo-nikolov , благодаря за съдействието. Добавих int за дължината на string-а. Преди това съм сравнявал само първите 2 и последните 2 букви.

2022-05-29 08:10 UTC, valyo-nikolov commented on src/homework_Lesson_5/ProgramValidatesPalindrome.java
> +        if (word.charAt(i) != word.charAt(word.length()-i-1)) {
Отлично!

2022-05-29 08:16 UTC, merged