Homework_Lesson_8
PGDimitrov/PetarDimitrov pull request #7
Opened 2022-06-12 22:29 UTC by PGDimitrov

Homework_Lesson_8

2022-06-13 06:21 UTC, valyo-nikolov requested changes
Оправи двата коментара които ти оставих. Справил си се добре като цяло!

2022-06-13 06:21 UTC, valyo-nikolov commented on src/homework_Lesson_8_Exercise_1/Square.java
> +    public Square(String color, boolean filled, double width, double length, double side) {
Тук може да ползваш полиморфизъм и да създадеш отделен нов Конструктор в който не подаваш width и length. Същото ще тр да направиш и в Правоъгълника понеже го наследяваш

2022-06-13 06:21 UTC, valyo-nikolov commented on src/homework_Lesson_8_Exercise_2/Employee.java
> +    public void raiseSalary () {
тук преправи метода да му се подава динамично процента на увеличение

2022-06-18 14:14 UTC, merged

2022-06-18 14:29 UTC, PGDimitrov commented on src/homework_Lesson_8_Exercise_1/Square.java
> +    public Square(String color, boolean filled, double width, double length, double side) {
Здравей @valyo-nikolov ,
направих промените, но без да искам го качих директно на master. Да го ревъртна или ще можеш да го погледнеш?

2022-06-18 14:29 UTC, PGDimitrov commented on src/homework_Lesson_8_Exercise_2/Employee.java
> +    public void raiseSalary () {
Здравей @valyo-nikolov ,
направих промените, но без да искам го качих директно на master. Да го ревъртна или ще можеш да го погледнеш?

2022-06-18 14:54 UTC, PGDimitrov commented on src/homework_Lesson_8_Exercise_1/Square.java
> +    public Square(String color, boolean filled, double width, double length, double side) {
Ако има нещо за корекция ще направя нов ПР.

2022-06-18 14:54 UTC, PGDimitrov commented on src/homework_Lesson_8_Exercise_2/Employee.java
> +    public void raiseSalary () {
Ако има нещо за корекция ще направя нов ПР.

2022-06-19 09:22 UTC, valyo-nikolov commented on src/homework_Lesson_8_Exercise_2/Employee.java
> +    public void raiseSalary () {
Ок, мерси Пешо - за сега всичко е точно